### ISSUE TITLE
How to use alarm?

### ISSUE THREAD

**Issue by chabad360** [cleroux/rtc#1]
It's a little unclear how to use the alarms. Only the `NewTimerAt` function actually waits for the alarm; The fd is private, so I can't even wait for the alarm myself, if I create an `rtc` (which itself is private, so I can't pass it around).

Is this still maintained? Or should I fork it and do what I need?

**Comment by cleroux** [comment]
There's an example here: https://github.com/cleroux/rtc/blob/main/timer_test.go#L11-L22

I never really used the timer or alarms so I admit it was not really in a polished state.  I was mostly interested in the ticker functionality when I wrote this and I included the timer/alarms because it was quite similar.  I've fixed a couple things related to the timer.  I believe you should be able to use it now.

I am open to suggestions or pull requests if you would like to provide them.  Thanks for the feedback.

**Comment by cleroux** [comment]
I'm assuming you have found your solution so I'm closing this issue.  Please feel free to open a new issue if something else comes up.
